### ISSUE TITLE
Terminology: 'Transparent Statement' -> 'Registered Statement'

### ISSUE THREAD

**Issue by kaywilliams** [ietf-wg-scitt/draft-ietf-scitt-architecture#20] opened 2023-03-06 17:22 UTC
In describing to lay audiences, I have found it easier to use the term 'registered statement' rather than 'transparent statement'. It reduces the number of concepts needed for understanding. Here is the workflow description I have been using:

User creates a statement
User signs a statement
User registers a statement on a transparency registry. Prior to registration, the statement is evaluated against registration policy.
User receives a receipt of registration
User shares a registered statement with interested parties
Auditors and others query the transparency registry to get a history of registered statements

See related comment on Issue #16

**Comment by SteveLasker** [comment] 2023-03-08 22:34
Thanks @kaywilliams. As the list of issues is growing, do you mind converging this discussion in #8?

**Comment by kaywilliams** [comment] 2023-03-08 22:36
I don't mind, but please note that Henk did ask me to create a separate issue. So, perhaps we check with him first?

**Comment by SteveLasker** [comment] 2023-03-08 22:38
@henkbirkholz, any reason to keep this separate from #8?

**Comment by SteveLasker** [comment] 2023-03-10 01:29
Resolving as a dupe of the #8 discussion and closing just to centralize common discussions. 
@kaywilliams, please review and copy your points to that issue. Also, please note the currently merged updates which use Statement.

**Closed by SteveLasker** 2023-03-10 01:29 UTC
Labels: duplicate

**Comment by kaywilliams** [comment] 2023-03-13 23:00
Added comment to #8
